#!/bin/bash
VERSION=0.1.0
TMPDIR=.tmp
PYLZMA=pylzma-$VERSION
mkdir $TMPDIR
svn export http://svn.fancycode.com/repos/python/pylzma/tags/v0_1_0 $TMPDIR/$PYLZMA
cd $TMPDIR
echo $VERSION > $PYLZMA/version.txt
tar czf $PYLZMA.tar.gz $PYLZMA
cd ..
cp $TMPDIR/$PYLZMA.tar.gz .
rm -rf $TMPDIR
